version: '3'

services:
  app:
    image: 'backend:dev'
    build:
      context: .
    container_name: 'backend'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SRPING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SRPING_DATASOURCE_USERNAME=root
      - SRPING_DATASOURCE_PASSWORD=toor
      - SRPING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: 'postgres:latest'
    container_name: 'database'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=backend